version: "3.8"
services:
 rabbitmq:
    image: "rabbitmq:3.11.6-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'

volumes:
  rabbitmq_data:
