logs:
    consoleLoggingEnabled: true
    fileLoggingEnabled: true
    directory: "/tmp/mock-server-logs"
    filename: "log"
    maxSize: 500
    maxBackups: 5
    maxAge: 30

pool:
    r_workers: 50
    w_workers: 50
    read_timeout: 10s
    write_timeout: 10s
    disable_task: 5s

brokers:
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"

coderun:
    worker_cnt: 10
    docker_container:
        cpu_limit: 0.5
        memory_limit: 200
