logs:
    level: 1
    consoleLoggingEnabled: false
    fileLoggingEnabled: true
    directory: "/tmp/mock-server-logs"
    filename: "mock-server-log"
    maxSize: 500
    maxBackups: 5
    maxAge: 30

use_components:
    server: true
    brokers: true
    coderun: true

brokers:
    scheduler:
        r_workers: 50
        w_workers: 50
        read_timeout: 10s
        write_timeout: 10s

    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"

    kafka:
        host: "localhost"
        port: 9092
        client_id: "client"
        group_id: "group"

coderun:
    worker_cnt: 1
    worker:
        handle_timeout: 10s
        container:
            cpu_limit: 0.5
            memory_limit_mb: 200

server:
    addr: "127.0.0.1:1337"
    accept_timeout: 20s
    response_timeout: 20s
    deploy_production: true

database:
    inmemory: true
    cache_size: 100
